### ISSUE TITLE
关于DomainSpecific Feature Aggregation的代码位置

### ISSUE THREAD

**Issue by Sandy-program** [HAIV-Lab/DPM#2]
作者您好，您的工作十分亮眼并且我对这篇工作十分感兴趣。正如论文中讲到，您通过feature aggregation来得到特定于领域的特征，不知道您是否方便指出feature aggregation的代码具体位置？十分感谢您的帮助！

**Comment by xuzhuoxuzhuo** [comment]
您好!  DPM-T 的DSFA : 
     .\DPM-T\trainer\DPM.py  
          def forward（...）
           295-305行，
DPM-F 的DSFA: 
      .\DPM-F\utils\dpm_core.py
        def get_ood_scores_DPM(...),
        240-245行

**Comment by Sandy-program** [comment]
非常你的帮助Thanks♪(･ω･)ﾉ
